name: "Lint and run tests"
on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        run: |
          pip install poetry==2.2.1 ruff==0.13.2
          poetry install
      - name: Lint with ruff
        run: |
          ruff --format=github --target-version=py313 .
        continue-on-error: true
      - name: Run tests
        run: |
          coverage run -m pytest -v -s
      - name: Generate coverage report
        run: |
          coverage report -m
